### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rubandurai27** [anime-republic/MIRROR-HUNTER#29]
Deploy error using workflow method . Please solve the issue

**Comment by yuno74** [comment]
what issues you get,I mean error

**Comment by rinrinx** [comment]
workflow does not work, I deployed manually

**Comment by yuno74** [comment]
do you fork repo and fill all workflows vars in secret?

**Comment by rinrinx** [comment]
Yes bro but not work

**Comment by yuno74** [comment]
@rinrinx what error show at workflow

**Comment by rinrinx** [comment]
name: Manually Deploy to heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
        env:
          HD_BOT_TOKEN: ${{secrets.BOT_TOKEN}}
          HD_GDRIVE_FOLDER_ID: ${{secrets.GDRIVE_FOLDER_ID}}
          HD_OWNER_ID: ${{secrets.OWNER_ID}}
          HD_DOWNLOAD_DIR: ${{secrets.DOWNLOAD_DIR}}
          HD_DOWNLOAD_STATUS_UPDATE_INTERVAL: ${{secrets.DOWNLOAD_STATUS_UPDATE_INTERVAL}}
          HD_AUTO_DELETE_MESSAGE_DURATION: ${{secrets.AUTO_DELETE_MESSAGE_DURATION}}
          HD_AUTO_DELETE_UPLOAD_MESSAGE_DURATION: ${{secrets.AUTO_DELETE_UPLOAD_MESSAGE_DURATION}}
          HD_IS_TEAM_DRIVE: ${{secrets.IS_TEAM_DRIVE}}
          HD_TELEGRAM_API: ${{secrets.TELEGRAM_API}}
          HD_TELEGRAM_HASH: ${{secrets.TELEGRAM_HASH}}
          HD_AUTHORIZED_CHATS: ${{secrets.AUTHORIZED_CHATS}}
          HD_LEECH_LOG: ${{secrets.LEECH_LOG}}
          HD_BOT_PM: ${{secrets.BOT_PM}}


I had to do it like this for deploying heroku


only normal config.env or config url doesn't work unfortunately

**Comment by yuno74** [comment]
@rinrinx that workflow seems edited

**Comment by rinrinx** [comment]
yes, i were able to distribute in this way, your workflow is not working

**Comment by yuno74** [comment]
@yuno74 just fill heroku api,heroku app name, heroku email

config url fill at Heroku

**Comment by rinrinx** [comment]
Heroku does not see the env values, most likely the problem is with the config, because after deploying, the config values ​​are not uploaded to heroku.

**Comment by yuno74** [comment]
@rinrinx done just copypaste workflow to your repo

**Comment by rinrinx** [comment]
The one I am currently editing is working.  but the workflow you added is not working. It freezes the wrong env values

**Comment by rinrinx** [comment]
can you fix kardrsim auto mirror status

**Comment by rinrinx** [comment]
can you fix bro auto mirror status

**Comment by rubandurai27** [comment]
![Screenshot_2022-04-15-15-17-02-258_com android chrome](https://user-images.githubusercontent.com/77948100/163556548-bfdd154b-d059-44ef-8936-ff79453ef91f.jpg)
