### ISSUE TITLE
Workflow not work

### ISSUE THREAD

**Issue by rinrinx** [anime-republic/MIRROR-HUNTER#30]
![Screenshot_20220415-095721_HManager](https://user-images.githubusercontent.com/91373907/163534026-9b385a0c-4652-4db2-b973-48e15cefef74.jpg)

I tried again, it doesn't work.  You can look at the log.

**Comment by yuno74** [comment]
even fill config_url?

**Comment by rinrinx** [comment]
yes I did.  still same problem

**Comment by rinrinx** [comment]
![Screenshot_20220415-100214_Chrome Dev](https://user-images.githubusercontent.com/91373907/163535344-33c9e50e-4daf-4c28-9f01-69681bb49a8f.jpg)

**Comment by yuno74** [comment]
try add that vars in heroku

**Comment by rinrinx** [comment]
yes I already add heroku but it works like this
