### ISSUE TITLE
How to solve this

### ISSUE THREAD

**Issue by yogeshmirro** [anime-republic/MIRROR-HUNTER#32]
![Screenshot_2022-04-22-23-43-40-176_com android chrome](https://user-images.githubusercontent.com/101546464/164771531-078993b8-e81c-4cf6-bd10-bb43a1b892bc.jpg)

**Comment by yogeshmirro** [comment]
Plz help

**Comment by yuno74** [comment]
@yogeshmirro you need enter config_url at Heroku

**Comment by yogeshmirro** [comment]
![Screenshot_2022-04-23-08-26-02-048_com android chrome](https://user-images.githubusercontent.com/101546464/164873088-ee4d16a9-e0b2-4b67-a587-f2fc8f31ed82.jpg)
![Screenshot_2022-04-23-08-14-19-729_com android chrome](https://user-images.githubusercontent.com/101546464/164873090-5ff24532-60e0-491b-bdb2-83f1c4c60362.jpg)

**Comment by yogeshmirro** [comment]
See

**Comment by yuno74** [comment]
@yogeshmirro if you already fill config.env from repo just remove config_url from heroku vars

**Comment by yogeshmirro** [comment]
Can u give me ur tg account username I send u ss and better discussion there

**Comment by rinrinx** [comment]
Endişelenmeyin, depo henüz tamamlanmadı.  Son güncellemeden sonra ayna bozuldu.  ve birkaç hata daha.

**Comment by rinrinx** [comment]
Don't worry, the repo is not complete yet. After the last update, the mirror is broken. and a few more errors.

**Comment by yogeshmirro** [comment]
Yes some cmd not working like mirror unzipmirror leechunzip etc

**Comment by yuno74** [comment]
@yogeshmirro will fix all tonight

**Comment by yogeshmirro** [comment]
Aur ek feature aur add kr dijiyega

**Comment by yogeshmirro** [comment]
Jo bhi user leech kre use bot direct pm m aise hi send na kre 
Phle uska link link shortner se short kre phir short kiya hua link user ko pm m send kre 
Ye feature kaafi helpful rhega 
Plz ese add kr dena
