### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by yogeshmirro** [anime-republic/MIRROR-HUNTER#38]
Bhai plz ye feature daal do ki bot pm m leech file send na kre , leech file ko url shortner se short krke short url ko pm m send kre
Plz

**Comment by yogeshmirro** [comment]
Nhi sir vo to sirf jo link mirror ki jaati h use hi short krta h 
M chaahta hu ki user jo leech kre use bot pm m as it is send na kre blki uske link ko short krke short kiye hue link ko pm m send kre 
Example jaise mere pass koi file sharing bot h 
To jo file sharing bot kisi file ka share link dega use phle m link shortner se short kruga phir us link ko user ko dunga 
To ye sb bot automatically kre 
 I Hope u understand what I want to say

**Comment by yuno74** [comment]
@yogeshmirro https://github.com/anime-republic/MIRROR-HUNTER/blob/5a58ea6500373e289d8558d7dbcd768d2209361d/config.env.sample#L77


try Fill this vars

**Comment by yogeshmirro** [comment]
> @yogeshmirro either write in english or get blocked

Send me ur tg username I tell u where in better way

**Comment by yogeshmirro** [comment]
> @yogeshmirro
> 
> https://github.com/anime-republic/MIRROR-HUNTER/blob/5a58ea6500373e289d8558d7dbcd768d2209361d/config.env.sample#L77
> 
> try Fill this vars

Ye jo method h ye only mirror cmd m work krta h leech cmd m nhi
