### ISSUE TITLE
Request!

### ISSUE THREAD

**Issue by weebmedico01** [anime-republic/MIRROR-HUNTER#41]
please sir add the INCOMPLETE_TASK_NOTIFIER in the repo it would be good useful to user knows the heroku bot restarted and again user have to mirror or leech or clone the data

**Comment by yuno74** [comment]
@weebmedico01 https://telegra.ph/file/bf25575f098e39a4c45b3.jpg

send message like that not enough?

**Comment by weebmedico01** [comment]
> @weebmedico01 https://telegra.ph/file/bf25575f098e39a4c45b3.jpg
> 
> send message like that not enough?

ya correct it make no sense 😅😅 
but i more request here can u fix this after mirror or leech complete the user link will automatically delete from group if it remain in the group it may be some helpful to the user

**Comment by yuno74** [comment]
@weebmedico01 that the reason why log channel make for

for make group clean (no more copyright issues)

**Comment by yuno74** [comment]
@yuno74 or if you still want just fill AUTO_DELETE_UPLOAD_MESSAGE_DURATION to -1 so message not gonna deleted forever

**Comment by weebmedico01** [comment]
> @weebmedico01 that the reason why log channel make for
> 
> for make group clean (no more copyright issues)

okk bro btw your repo is stable and work perfectly

**Comment by yuno74** [comment]
@weebmedico01 yup for now IG
