### ISSUE TITLE
ERROR BRO

### ISSUE THREAD

**Issue by Vision-Wizard** [anime-republic/MIRROR-HUNTER#49]
How to fix this issue bro
I filled all vars still this issue

![Screenshot_20220510_085748](https://user-images.githubusercontent.com/105115761/167537097-530839ab-db16-48ce-938c-bf4f96219a65.jpg)

**Comment by Tanujairam-TG** [comment]
![Screenshot_2022-05-10-15-30-43-329_com android chrome](https://user-images.githubusercontent.com/88611197/167603522-ec5b4d8c-ff5f-4819-88e2-a96052e38c5f.jpg)
Same issue coming for me to 
Request you to please fix the error bro

**Comment by Tanujairam-TG** [comment]
Set USE_SERVICE_ACCOUNT ="False"

**Comment by Vision-Wizard** [comment]
By the way Heroku suspended 3 times 🙂🙂

Sent from the all new AOL app for Android 
 
  On Wed, May 11, 2022 at 4:04 PM, ***@***.***> wrote:   


Set USE_SERVICE_ACCOUNT ="False"
